# K-MEANS CONFIGURATION
KMEANS_MIN_CLUSTERS = 2
KMEANS_MAX_CLUSTERS = 21
KMEANS_N_INIT = [10, 20]
KMEANS_MAX_ITER = [100,300,500]
KMEANS_BALANCED_MIN = 5
KMEANS_BALANCED_MAX = 15
KMEANS_BALANCED_MIN_SILHOUETTE = 0.2
# HIERARCHICAL CLUSTERING CONFIGURATION
HIER_MIN_CLUSTERS = 2
HIER_MAX_CLUSTERS = 21
HIER_LINKAGE_METHODS = ['ward', 'complete', 'average']
HIER_METRIC = ['euclidean']
HIER_BALANCED_MIN = 2
HIER_BALANCED_MAX = 15
HIER_BALANCED_MIN_SILHOUETTE = 0.2
# DBSCAN CONFIGURATION
DBSCAN_EPS_MIN_PERCENTILE = 60
DBSCAN_EPS_MAX_PERCENTILE = 95
DBSCAN_EPS_N_VALUES = 12
DBSCAN_MIN_SAMPLES = [3, 5, 10, 15, 20, 25, 35]
DBSCAN_MIN_CLUSTERS = 5
DBSCAN_MAX_CLUSTERS = 30
DBSCAN_MAX_NOISE_PCT = 30
OPTIMIZATION_METRIC = 'silhouette'
VERBOSE_TUNING = True